-- Poly: Italian glossary + example sentences
-- Run this in the Supabase SQL editor for your project.
--
-- NOTE: RLS is disabled, since this is a single-user personal tool
-- accessed with the anon key. Don't deploy it publicly without auth + RLS.
--
-- WARNING: this replaces the earlier "sentences notebook" schema with a
-- glossary (words) table plus example sentences linked to a word. Running
-- this will drop the old standalone sentences table and its data.

create extension if not exists pgcrypto;

drop table if exists cards;
drop table if exists activity_log;
drop table if exists settings;
drop table if exists sentences;
drop table if exists words;

-- Glossary: editable word list
create table if not exists words (
  id uuid primary key default gen_random_uuid(),
  it text not null,
  en text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists words_it_idx on words (lower(it));
alter table words disable row level security;

-- Example sentences for a given word
create table if not exists sentences (
  id uuid primary key default gen_random_uuid(),
  word_id uuid not null references words(id) on delete cascade,
  target_text text not null,
  native_text text,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists sentences_word_id_idx on sentences (word_id);
alter table sentences disable row level security;

-- Starter glossary: ~190 common Italian words
insert into words (it, en) values
  ('io', 'I'),
  ('tu', 'you'),
  ('lui', 'he'),
  ('lei', 'she'),
  ('noi', 'we'),
  ('voi', 'you all'),
  ('loro', 'they'),
  ('essere', 'to be'),
  ('avere', 'to have'),
  ('fare', 'to do'),
  ('dire', 'to say'),
  ('andare', 'to go'),
  ('potere', 'can'),
  ('volere', 'to want'),
  ('dovere', 'must'),
  ('sapere', 'to know'),
  ('stare', 'to stay'),
  ('vedere', 'to see'),
  ('venire', 'to come'),
  ('dare', 'to give'),
  ('mettere', 'to put'),
  ('prendere', 'to take'),
  ('parlare', 'to speak'),
  ('pensare', 'to think'),
  ('trovare', 'to find'),
  ('lasciare', 'to leave'),
  ('capire', 'to understand'),
  ('sentire', 'to hear'),
  ('chiedere', 'to ask'),
  ('restare', 'to remain'),
  ('portare', 'to bring'),
  ('tornare', 'to return'),
  ('guardare', 'to watch'),
  ('passare', 'to pass'),
  ('conoscere', 'to know (someone)'),
  ('vivere', 'to live'),
  ('credere', 'to believe'),
  ('finire', 'to finish'),
  ('arrivare', 'to arrive'),
  ('cercare', 'to search'),
  ('cominciare', 'to begin'),
  ('mangiare', 'to eat'),
  ('bere', 'to drink'),
  ('dormire', 'to sleep'),
  ('lavorare', 'to work'),
  ('aiutare', 'to help'),
  ('comprare', 'to buy'),
  ('scrivere', 'to write'),
  ('leggere', 'to read'),
  ('ascoltare', 'to listen'),
  ('giocare', 'to play'),
  ('camminare', 'to walk'),
  ('correre', 'to run'),
  ('ridere', 'to laugh'),
  ('piangere', 'to cry'),
  ('amare', 'to love'),
  ('di', 'of'),
  ('a', 'to'),
  ('da', 'from'),
  ('in', 'in'),
  ('con', 'with'),
  ('su', 'on'),
  ('per', 'for'),
  ('tra', 'between'),
  ('fra', 'among'),
  ('e', 'and'),
  ('o', 'or'),
  ('ma', 'but'),
  ('perché', 'because'),
  ('quindi', 'so'),
  ('se', 'if'),
  ('che', 'that'),
  ('anche', 'also'),
  ('però', 'however'),
  ('mentre', 'while'),
  ('molto', 'very'),
  ('poco', 'little'),
  ('bene', 'well'),
  ('male', 'badly'),
  ('sempre', 'always'),
  ('mai', 'never'),
  ('già', 'already'),
  ('ancora', 'still'),
  ('oggi', 'today'),
  ('ieri', 'yesterday'),
  ('domani', 'tomorrow'),
  ('qui', 'here'),
  ('lì', 'there'),
  ('adesso', 'now'),
  ('ora', 'now'),
  ('dopo', 'after'),
  ('prima', 'before'),
  ('presto', 'soon'),
  ('tardi', 'late'),
  ('forse', 'maybe'),
  ('davvero', 'really'),
  ('troppo', 'too much'),
  ('abbastanza', 'enough'),
  ('uno', 'one'),
  ('due', 'two'),
  ('tre', 'three'),
  ('quattro', 'four'),
  ('cinque', 'five'),
  ('sei', 'six'),
  ('sette', 'seven'),
  ('otto', 'eight'),
  ('nove', 'nine'),
  ('dieci', 'ten'),
  ('cento', 'one hundred'),
  ('chi', 'who'),
  ('cosa', 'what'),
  ('come', 'how'),
  ('dove', 'where'),
  ('quando', 'when'),
  ('quale', 'which'),
  ('quanto', 'how much'),
  ('casa', 'house'),
  ('tempo', 'time'),
  ('anno', 'year'),
  ('giorno', 'day'),
  ('persona', 'person'),
  ('uomo', 'man'),
  ('donna', 'woman'),
  ('bambino', 'child'),
  ('vita', 'life'),
  ('mano', 'hand'),
  ('occhio', 'eye'),
  ('parola', 'word'),
  ('lavoro', 'work'),
  ('mondo', 'world'),
  ('paese', 'country'),
  ('città', 'city'),
  ('strada', 'street'),
  ('acqua', 'water'),
  ('cibo', 'food'),
  ('amico', 'friend'),
  ('famiglia', 'family'),
  ('scuola', 'school'),
  ('libro', 'book'),
  ('macchina', 'car'),
  ('telefono', 'phone'),
  ('soldi', 'money'),
  ('buono', 'good'),
  ('cattivo', 'bad'),
  ('grande', 'big'),
  ('piccolo', 'small'),
  ('bello', 'beautiful'),
  ('brutto', 'ugly'),
  ('nuovo', 'new'),
  ('vecchio', 'old'),
  ('giovane', 'young'),
  ('alto', 'tall'),
  ('basso', 'short'),
  ('lungo', 'long'),
  ('facile', 'easy'),
  ('difficile', 'difficult'),
  ('importante', 'important'),
  ('diverso', 'different'),
  ('stesso', 'same'),
  ('primo', 'first'),
  ('ultimo', 'last'),
  ('vero', 'true'),
  ('felice', 'happy'),
  ('triste', 'sad'),
  ('ciao', 'hi'),
  ('grazie', 'thank you'),
  ('prego', 'you''re welcome'),
  ('scusa', 'sorry'),
  ('buongiorno', 'good morning'),
  ('buonasera', 'good evening'),
  ('buonanotte', 'good night'),
  ('arrivederci', 'goodbye'),
  ('certo', 'sure'),
  ('magari', 'maybe')
on conflict (lower(it)) do nothing;

-- Belt-and-suspenders: Supabase can auto-enable RLS on new tables, which
-- silently breaks the insert above. Make sure it's off after everything.
alter table words disable row level security;
alter table sentences disable row level security;
